name: Deploy
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - Name: Deploy to DigitalOcean
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: nihongo_api
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
